import type { AdminMenuItem } from '@/types/admin'

// Full capability inventory. Hidden tooling routes still depend on this source.
export const adminMenus: AdminMenuItem[] = [
  {
    key: 'dashboard',
    label: '工作台',
    icon: 'DataBoard',
    route: '/dashboard/index',
    menuPermission: 'menu.dashboard',
    pagePermission: 'page.dashboard.index',
  },
  {
    key: 'verify',
    label: '实名认证',
    icon: 'CircleCheck',
    menuPermission: 'menu.verify',
    children: [
      {
        key: 'verify-pending',
        label: '待审核',
        icon: 'CircleCheck',
        route: '/verify/pending',
        pagePermission: 'page.verify.pending',
      },
      {
        key: 'verify-history',
        label: '审核历史',
        icon: 'List',
        route: '/verify/history',
        pagePermission: 'page.verify.history',
      },
    ],
  },
  {
    key: 'referral',
    label: '邀请治理',
    icon: 'Connection',
    menuPermission: 'menu.referral',
    children: [
      {
        key: 'referral-records',
        label: '邀请记录',
        icon: 'Tickets',
        route: '/referral/records',
        pagePermission: 'page.referral.records',
      },
      {
        key: 'referral-risk',
        label: '异常邀请',
        icon: 'Warning',
        route: '/referral/risk',
        pagePermission: 'page.referral.risk',
      },
      {
        key: 'referral-policies',
        label: '邀请规则',
        icon: 'SetUp',
        route: '/referral/policies',
        pagePermission: 'page.referral.policies',
      },
      {
        key: 'referral-eligibility',
        label: '邀请资格',
        icon: 'Medal',
        route: '/referral/eligibility',
        pagePermission: 'page.referral.eligibility',
      },
    ],
  },
  {
    key: 'recruit',
    label: '招募治理',
    icon: 'Files',
    children: [
      {
        key: 'recruit-projects',
        label: '招募项目治理',
        icon: 'Files',
        route: '/recruit/projects',
        pagePermission: 'page.recruit.projects',
      },
      {
        key: 'recruit-roles',
        label: '招募角色治理',
        icon: 'Document',
        route: '/recruit/roles',
        pagePermission: 'page.recruit.roles',
      },
      {
        key: 'recruit-applies',
        label: '投递链路回看',
        icon: 'Avatar',
        route: '/recruit/applies',
        pagePermission: 'page.recruit.applies',
      },
    ],
  },
  {
    key: 'users',
    label: '用户管理',
    icon: 'UserFilled',
    menuPermission: 'menu.users',
    children: [
      {
        key: 'users-index',
        label: '业务用户',
        icon: 'UserFilled',
        route: '/users/index',
        pagePermission: 'page.users.index',
      },
    ],
  },
  {
    key: 'content',
    label: '页面配置',
    icon: 'MagicStick',
    menuPermission: 'menu.content',
    children: [
      {
        key: 'content-templates',
        label: '模板配置治理',
        icon: 'Files',
        route: '/content/templates',
        pagePermission: 'page.content.templates',
      },
      {
        key: 'content-publish-logs',
        label: '模板发布记录',
        icon: 'List',
        route: '/content/publish-logs',
        pagePermission: 'page.content.publish-logs',
      },
      {
        key: 'content-theme-tokens',
        label: '主题 Token',
        icon: 'Brush',
        route: '/content/theme-tokens',
        pagePermission: 'page.content.theme-tokens',
      },
      {
        key: 'content-share-artifacts',
        label: '分享产物配置',
        icon: 'Memo',
        route: '/content/share-artifacts',
        pagePermission: 'page.content.share-artifacts',
      },
      {
        key: 'content-contact-requests',
        label: '联系方式申请',
        icon: 'ChatDotRound',
        route: '/content/contact-requests',
        pagePermission: 'page.content.contact-requests',
      },
      {
        key: 'content-share-cards',
        label: '分享卡治理',
        icon: 'Postcard',
        route: '/content/share-cards',
        pagePermission: 'page.content.share-cards',
      },
    ],
  },
  {
    key: 'system',
    label: '系统管理',
    icon: 'Setting',
    menuPermission: 'menu.system',
    children: [
      {
        key: 'system-ai-resume-governance',
        label: 'AI 简历治理',
        icon: 'MagicStick',
        route: '/system/ai-resume-governance',
        pagePermission: 'page.system.ai-resume-governance',
      },
      {
        key: 'system-ai-image-providers',
        label: 'AI 生图模型配置',
        icon: 'Picture',
        route: '/system/ai-image-providers',
        pagePermission: 'page.system.ai-image-providers',
      },
      {
        key: 'system-admin-users',
        label: '后台账号治理',
        icon: 'Avatar',
        route: '/system/admin-users',
        pagePermission: 'page.system.admin-users',
      },
      {
        key: 'system-roles',
        label: '角色权限治理',
        icon: 'Postcard',
        route: '/system/roles',
        pagePermission: 'page.system.roles',
      },
      {
        key: 'system-operation-logs',
        label: '操作留痕审计',
        icon: 'List',
        route: '/system/operation-logs',
        pagePermission: 'page.system.operation-logs',
      },
    ],
  },
]

// Formal navigation projection. Hidden tooling routes still live in adminMenus/router.
export const adminSidebarMenus: AdminMenuItem[] = [
  {
    key: 'dashboard-index',
    label: '仪表盘',
    icon: 'DataBoard',
    section: 'overview',
    route: '/dashboard/index',
    menuPermission: 'menu.dashboard',
    pagePermission: 'page.dashboard.index',
  },
  {
    key: 'dashboard-analytics',
    label: '数据分析',
    icon: 'Histogram',
    section: 'overview',
    route: '/dashboard/analytics',
    menuPermission: 'menu.dashboard',
    pagePermission: 'page.dashboard.index',
  },
  {
    key: 'users-index',
    label: '用户管理',
    icon: 'UserFilled',
    section: 'growth',
    route: '/users/index',
    menuPermission: 'menu.users',
    pagePermission: 'page.users.index',
  },
  {
    key: 'content-share-cards',
    label: '分享内容',
    icon: 'Postcard',
    section: 'growth',
    route: '/content/share-cards',
    menuPermission: 'menu.content',
    pagePermission: 'page.content.share-cards',
  },
  {
    key: 'content-templates',
    label: '风格模板',
    icon: 'Files',
    section: 'operate',
    route: '/content/templates',
    menuPermission: 'menu.content',
    pagePermission: 'page.content.templates',
  },
  {
    key: 'operate-actions',
    label: '运营动作',
    icon: 'MagicStick',
    section: 'operate',
    route: '/operate/actions',
    pagePermission: 'page.dashboard.index',
  },
  {
    key: 'system-settings',
    label: '系统设置',
    icon: 'Setting',
    section: 'operate',
    route: '/system/settings',
    menuPermission: 'menu.system',
    anyPagePermissions: [
      'page.verify.pending',
      'page.content.contact-requests',
      'page.content.templates',
      'page.content.share-cards',
      'page.system.admin-users',
      'page.system.roles',
      'page.system.operation-logs',
      'page.system.ai-resume-governance',
      'page.system.ai-image-providers',
    ],
  },
  {
    key: 'system-ai-image-providers',
    label: 'AI 生图配置',
    icon: 'Picture',
    section: 'operate',
    route: '/system/ai-image-providers',
    menuPermission: 'menu.system',
    anyPagePermissions: [
      'page.system.ai-image-providers',
    ],
  },
]
